# Generated by Django 3.0.4 on 2021-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kijiwenongwa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tittle_tag',
            field=models.CharField(default='kijiwenongwa', max_length=50),
        ),
    ]
