# Generated by Django 3.0.4 on 2021-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kijiwenongwa_app', '0006_auto_20210314_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='This is the snippet', max_length=255),
        ),
    ]
