# Generated by Django 3.0.4 on 2021-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kijiwenongwa_app', '0012_auto_20210504_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
